# This is a sample aws-auth-patch.yml file. 
# Actual aws-auth-patch.yml will be created at /System/Volumes/Data/private/tmp/aws-auth-patch.yml path.

apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::201046244662:role/UdacityFlaskDeployCBKubectlRole
      username: build      
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::201046244662:role/eksctl-project2-nodegroup-ng-f68a-NodeInstanceRole-1MRR27JEA9GD4
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-02-26T07:40:38Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "5992"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 5bf363cb-504c-4289-93ce-74257aff0de4
